@echo off

echo.
echo Testing /health endpoint...
powershell -Command "$body = '{\"resource\": \"/health\", \"path\": \"/health\", \"httpMethod\": \"GET\", \"headers\": {\"Accept\": \"application/json\", \"Content-Type\": \"application/json\"}, \"multiValueHeaders\": {}, \"queryStringParameters\": null, \"multiValueQueryStringParameters\": null, \"pathParameters\": null, \"stageVariables\": null, \"requestContext\": {\"resourceId\": \"abc123\", \"resourcePath\": \"/health\", \"httpMethod\": \"GET\", \"extendedRequestId\": \"test\", \"requestTime\": \"09/Apr/2015:12:34:56 +0000\", \"path\": \"/test/health\", \"accountId\": \"123456789012\", \"protocol\": \"HTTP/1.1\", \"stage\": \"test\", \"domainPrefix\": \"testPrefix\", \"requestTimeEpoch\": 1428582896000, \"requestId\": \"c6af9ac6-7b61-11e6-9a41-93e8deadbeef\", \"identity\": {\"sourceIp\": \"127.0.0.1\"}, \"domainName\": \"testPrefix.testDomainName\", \"apiId\": \"1234567890\"}, \"body\": null, \"isBase64Encoded\": false}'; Invoke-RestMethod -Uri 'http://localhost:9000/2015-03-31/functions/function/invocations' -Method POST -Body $body -ContentType 'application/json'"

echo.
echo Testing root endpoint...
powershell -Command "$body = '{\"resource\": \"/\", \"path\": \"/\", \"httpMethod\": \"GET\", \"headers\": {\"Accept\": \"application/json\", \"Content-Type\": \"application/json\"}, \"multiValueHeaders\": {}, \"queryStringParameters\": null, \"multiValueQueryStringParameters\": null, \"pathParameters\": null, \"stageVariables\": null, \"requestContext\": {\"resourceId\": \"abc123\", \"resourcePath\": \"/\", \"httpMethod\": \"GET\", \"extendedRequestId\": \"test\", \"requestTime\": \"09/Apr/2015:12:34:56 +0000\", \"path\": \"/test/\", \"accountId\": \"123456789012\", \"protocol\": \"HTTP/1.1\", \"stage\": \"test\", \"domainPrefix\": \"testPrefix\", \"requestTimeEpoch\": 1428582896000, \"requestId\": \"c6af9ac6-7b61-11e6-9a41-93e8deadbeef\", \"identity\": {\"sourceIp\": \"127.0.0.1\"}, \"domainName\": \"testPrefix.testDomainName\", \"apiId\": \"1234567890\"}, \"body\": null, \"isBase64Encoded\": false}'; Invoke-RestMethod -Uri 'http://localhost:9000/2015-03-31/functions/function/invocations' -Method POST -Body $body -ContentType 'application/json'"
