name: Backend

on:
  push:
    paths: ["backend/**"]
  pull_request:
    paths: ["backend/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run test_lambda.py

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Get ECR Repository URL
        id: ecr
        run: |
          ECR_URI=$(aws ecr describe-repositories --repository-names leonidas-backend --query 'repositories[0].repositoryUri' --output text)
          echo "ecr_uri=$ECR_URI" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        run: |
          # Build and push container
          docker build -t leonidas-backend .
          docker tag leonidas-backend:latest ${{ steps.ecr.outputs.ecr_uri }}:latest
          docker push ${{ steps.ecr.outputs.ecr_uri }}:latest
          
          echo "✅ Container image pushed to ECR successfully!"
          echo "📦 Image URI: ${{ steps.ecr.outputs.ecr_uri }}:latest"
          echo "🔄 Ready to uncomment Lambda function in infrastructure"
