name: Backend

on:
  push:
    paths: ["backend/**"]
  pull_request:
    paths: ["backend/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com
          
      - name: Build and Push Docker Image
        run: |
          # Get ECR repository URL from Terraform
          cd ../infrastructure
          ECR_URI=$(terraform output -raw ecr_repository_url)
          cd ../backend
          
          # Build and push container
          docker build -t leonidas-backend .
          docker tag leonidas-backend:latest $ECR_URI:latest
          docker push $ECR_URI:latest
          
      - name: Update Lambda Function
        run: |
          cd ../infrastructure
          FUNCTION_NAME=$(terraform output -raw lambda_function_name)
          ECR_URI=$(terraform output -raw ecr_repository_url)
          
          # Update Lambda to use new image
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --image-uri $ECR_URI:latest \
            --region ap-southeast-1
