name: Destroy Infrastructure

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      confirm:
        description: 'Type "DESTROY" to confirm'
        required: true
        default: ''

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DESTROY'
    defaults:
      run:
        working-directory: infrastructure
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_github_token: ${{ secrets.AMPLIFY_TOKEN }}
        TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        TF_VAR_github_repository: ${{ secrets.REPO_NAME }}