name: Frontend

on:
  push:
    paths: ["frontend/**"]
  pull_request:
    paths: ["frontend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Get API URL from Terraform
        run: |
          cd ../infrastructure
          terraform init
          API_URL=$(terraform output -raw api_gateway_url)
          echo "API_URL=$API_URL" >> $GITHUB_ENV

      - name: Build for production
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ env.API_URL }}

      - name: Update Amplify Environment Variables
        run: |
          APP_ID=$(aws amplify list-apps --query "apps[?name=='leonidas-frontend'].appId" --output text)
          aws amplify update-app --app-id $APP_ID --environment-variables NEXT_PUBLIC_API_URL=${{ env.API_URL }}
          echo "✅ Updated Amplify environment variables"
          echo "🌐 Amplify will auto-deploy from GitHub push"
